const usersList = [
  {
    firstName: 'Margalit',
    lastName: 'Ellerby',
    email: 'mellerby0@home.pl',
    imageURL: 'http://dummyimage.com/100x100.png/dddddd/000000',
    password: 'JAsx1CGtI',
    isAdmin: false,
    role: 'user',
    currencyId: 4,
  },
  {
    firstName: 'Travus',
    lastName: 'Seater',
    email: 'tseater1@nature.com',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: 'Q4dgqiiH',
    isAdmin: false,
    role: 'user',
    currencyId: 1,
  },
  {
    firstName: 'Joellyn',
    lastName: 'Moreno',
    email: 'jmoreno2@baidu.com',
    imageURL: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    password: 'LVuVthfVZDX',
    isAdmin: false,
    role: 'engineer',
    currencyId: 4,
  },
  {
    firstName: 'Ford',
    lastName: 'Mulkerrins',
    email: 'fmulkerrins3@washington.edu',
    imageURL: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    password: 'sEuPQrptboE',
    isAdmin: false,
    role: 'engineer',
    currencyId: 2,
  },
  {
    firstName: 'Karina',
    lastName: 'Mouser',
    email: 'kmouser4@time.com',
    imageURL: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    password: 'vzyMJQ8GFu',
    isAdmin: false,
    role: 'user',
    currencyId: 2,
  },
  {
    firstName: 'Kelbee',
    lastName: 'Tillerton',
    email: 'ktillerton5@wix.com',
    imageURL: 'http://dummyimage.com/100x100.png/dddddd/000000',
    password: 'r8UCIweOEa',
    isAdmin: true,
    role: 'user',
    currencyId: 1,
  },
  {
    firstName: 'Dino',
    lastName: 'Alleyn',
    email: 'dalleyn6@cocolog-nifty.com',
    imageURL: 'http://dummyimage.com/100x100.png/dddddd/000000',
    password: '09Oa3HSCKSV',
    isAdmin: false,
    role: 'user',
    currencyId: 3,
  },
  {
    firstName: 'Craig',
    lastName: 'Walkling',
    email: 'cwalkling7@zdnet.com',
    imageURL: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    password: 'IbIouMROgvs',
    isAdmin: false,
    role: 'user',
    currencyId: 1,
  },
  {
    firstName: 'Maxie',
    lastName: 'Bazley',
    email: 'mbazley8@miitbeian.gov.cn',
    imageURL: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    password: 'EAuHasdavNK',
    isAdmin: false,
    role: 'user',
    currencyId: 2,
  },
  {
    firstName: 'Inna',
    lastName: 'Klimko',
    email: 'iklimko9@uiuc.edu',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: 'BwsVLOAnUb',
    isAdmin: false,
    role: 'user',
    currencyId: 4,
  },
  {
    firstName: 'Cherilyn',
    lastName: 'Alcock',
    email: 'calcocka@google.com.br',
    imageURL: 'http://dummyimage.com/100x100.png/dddddd/000000',
    password: 'BJX8HBIsa',
    isAdmin: false,
    role: 'engineer',
    currencyId: 3,
  },
  {
    firstName: 'Jolynn',
    lastName: 'MacClay',
    email: 'jmacclayb@earthlink.net',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: '6CCHhbMMr5S',
    isAdmin: true,
    role: 'engineer',
    currencyId: 4,
  },
  {
    firstName: 'Urbano',
    lastName: 'Rominov',
    email: 'urominovc@mediafire.com',
    imageURL: 'http://dummyimage.com/100x100.png/dddddd/000000',
    password: 'Z1mXEowc',
    isAdmin: false,
    role: 'engineer',
    currencyId: 4,
  },
  {
    firstName: 'Cloris',
    lastName: 'Schafer',
    email: 'cschaferd@comcast.net',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: '5rSXIFIpvIj',
    isAdmin: false,
    role: 'engineer',
    currencyId: 4,
  },
  {
    firstName: 'Spenser',
    lastName: 'Neighbour',
    email: 'sneighboure@google.com.hk',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: 'T2V2y36To',
    isAdmin: false,
    role: 'user',
    currencyId: 2,
  },
  {
    firstName: 'Jorgan',
    lastName: 'Laight',
    email: 'jlaightf@cafepress.com',
    imageURL: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    password: 'cKyCasdfasecvaWF',
    isAdmin: false,
    role: 'user',
    currencyId: 3,
  },
  {
    firstName: 'Alexia',
    lastName: 'Bentson',
    email: 'abentsong@geocities.jp',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: '5nWipdDEjGu',
    isAdmin: false,
    role: 'engineer',
    currencyId: 4,
  },
  {
    firstName: 'Orelle',
    lastName: 'Ouver',
    email: 'oouverh@answers.com',
    imageURL: 'http://dummyimage.com/100x100.png/dddddd/000000',
    password: 'YYRtgWjKNeA',
    isAdmin: false,
    role: 'engineer',
    currencyId: 4,
  },
  {
    firstName: 'Sheila-kathryn',
    lastName: 'Jacklings',
    email: 'sjacklingsi@netvibes.com',
    imageURL: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    password: 'kmEiRsZX2t',
    isAdmin: false,
    role: 'engineer',
    currencyId: 2,
  },
  {
    firstName: 'Porter',
    lastName: 'Tabram',
    email: 'ptabramj@biblegateway.com',
    imageURL: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
    password: 'J3wA46jk3moM',
    isAdmin: false,
    role: 'user',
    currencyId: 2,
  },
  {
    firstName: 'Harrison',
    lastName: 'Sambath',
    email: 'hsambathk@time.com',
    imageURL: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    password: 'jTdclNCyiDR',
    isAdmin: true,
    role: 'engineer',
    currencyId: 1,
  },
  {
    firstName: 'Lesly',
    lastName: 'Mander',
    email: 'lmanderl@hugedomains.com',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: '24l6gtmKW',
    isAdmin: false,
    role: 'user',
    currencyId: 1,
  },
  {
    firstName: 'Rubia',
    lastName: 'Fawson',
    email: 'rfawsonm@mlb.com',
    imageURL: 'http://dummyimage.com/100x100.png/dddddd/000000',
    password: '0qVNbasdfLP',
    isAdmin: true,
    role: 'user',
    currencyId: 1,
  },
  {
    firstName: 'Nikolos',
    lastName: 'Banbury',
    email: 'nbanburyn@a8.net',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: 'vQ4I3nvFv',
    isAdmin: false,
    role: 'user',
    currencyId: 1,
  },
  {
    firstName: 'Malvin',
    lastName: 'Paragreen',
    email: 'mparagreeno@mac.com',
    imageURL: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    password: 'qsHbeGCS4',
    isAdmin: false,
    role: 'user',
    currencyId: 2,
  },
];

module.exports = usersList;
