const shipment = [
  {
    street1: '12 Blaine Pass',
    city: 'Schenectady',
    state: 'New York',
    zip: '12325',
    isDefault: 'true',
  },
  {
    street1: '00 Namekagon Place',
    street2: 'PO Box 46091',
    city: 'Washington',
    state: 'District of Columbia',
    zip: '20062',
    isDefault: 'true',
  },
  {
    street1: '367 Upham Place',
    street2: 'Room 924',
    city: 'Saint Louis',
    state: 'Missouri',
    zip: '63167',
    isDefault: 'true',
  },
  {
    street1: '0 Kensington Point',
    city: 'Jacksonville',
    state: 'Florida',
    zip: '32230',
    isDefault: 'true',
  },
  {
    street1: '6 8th Pass',
    street2: 'Apt 185',
    city: 'Davenport',
    state: 'Iowa',
    zip: '52804',
    isDefault: 'true',
  },
  {
    street1: '7194 Stang Park',
    street2: 'PO Box 97737',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    zip: '15220',
    isDefault: 'true',
  },
  {
    street1: '1481 Kenwood Lane',
    street2: 'Apt 226',
    city: 'El Paso',
    state: 'Texas',
    zip: '88553',
    isDefault: 'true',
  },
  {
    street1: '6 Eagle Crest Avenue',
    street2: 'Apt 491',
    city: 'Raleigh',
    state: 'North Carolina',
    zip: '27605',
    isDefault: 'true',
  },
  {
    street1: '66316 Leroy Street',
    street2: 'Room 1192',
    city: 'Riverside',
    state: 'California',
    zip: '92505',
    isDefault: 'true',
  },
  {
    street1: '8 Corscot Lane',
    street2: 'PO Box 16537',
    city: 'Alexandria',
    state: 'Virginia',
    zip: '22301',
    isDefault: 'true',
  },
  {
    street1: '9331 Pankratz Road',
    city: 'Orlando',
    state: 'Florida',
    zip: '32813',
    isDefault: 'true',
  },
  {
    street1: '3038 Shasta Hill',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    zip: '19120',
    isDefault: 'true',
  },
  {
    street1: '2 Birchwood Circle',
    city: 'Bridgeport',
    state: 'Connecticut',
    zip: '06673',
    isDefault: 'true',
  },
  {
    street1: '096 Darwin Point',
    street2: '15th Floor',
    city: 'Phoenix',
    state: 'Arizona',
    zip: '85025',
    isDefault: 'true',
  },
  {
    street1: '6 Kropf Drive',
    street2: 'Apt 1048',
    city: 'Tulsa',
    state: 'Oklahoma',
    zip: '74126',
    isDefault: 'true',
  },
  {
    street1: '7147 Chive Terrace',
    street2: 'Suite 75',
    city: 'Peoria',
    state: 'Arizona',
    zip: '85383',
    isDefault: 'true',
  },
  {
    street1: '45120 Victoria Point',
    street2: 'Apt 253',
    city: 'Ogden',
    state: 'Utah',
    zip: '84409',
    isDefault: 'true',
  },
  {
    street1: '71 Saint Paul Trail',
    city: 'Spring',
    state: 'Texas',
    zip: '77388',
    isDefault: 'true',
  },
  {
    street1: '867 Maple Crossing',
    street2: 'Apt 1216',
    city: 'Cincinnati',
    state: 'Ohio',
    zip: '45254',
    isDefault: 'true',
  },
  {
    street1: '59344 Sycamore Lane',
    street2: 'Room 1616',
    city: 'Albany',
    state: 'New York',
    zip: '12247',
    isDefault: 'true',
  },
  {
    street1: '8128 Harbort Street',
    street2: 'Room 449',
    city: 'Greensboro',
    state: 'North Carolina',
    zip: '27425',
    isDefault: 'true',
  },
  {
    street1: '79817 Westerfield Lane',
    street2: 'PO Box 17589',
    city: 'El Paso',
    state: 'Texas',
    zip: '88514',
    isDefault: 'true',
  },
  {
    street1: '37189 Mcbride Center',
    city: 'Charlotte',
    state: 'North Carolina',
    zip: '28210',
    isDefault: 'true',
  },
  {
    street1: '43 Mariners Cove Drive',
    city: 'Peoria',
    state: 'Arizona',
    zip: '85383',
    isDefault: 'true',
  },
  {
    street1: '169 Westerfield Street',
    street2: '16th Floor',
    city: 'Charlotte',
    state: 'North Carolina',
    zip: '28235',
    isDefault: 'true',
  },
];
module.exports = shipment;